// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateApi.Data;

#nullable disable

namespace RealEstateApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514105908_InquiryConfirmationPropertyAware")]
    partial class InquiryConfirmationPropertyAware
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateApi.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastUpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("RealEstateApi.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AreaInCents")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal?>("AreaInSqFt")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("AssignedToVerifyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedToVerifyUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LegalStatus")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MarketingPlan")
                        .HasColumnType("integer");

                    b.Property<List<string>>("NearbyLandmarks")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PricePerCent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<bool>("RoadAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("SubmitterEmail")
                        .HasColumnType("text");

                    b.Property<string>("SubmitterName")
                        .HasColumnType("text");

                    b.Property<string>("SubmitterPhone")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerificationDoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("AssignedToVerifyUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kottar, Near NH 44",
                            ApprovalStatus = "Approved",
                            AreaInCents = 15m,
                            AreaInSqFt = 6534m,
                            City = "Nagercoil",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prime land parcel near NH 44 with excellent road frontage. Clear legal documents available.",
                            District = "Kanyakumari",
                            Features = new List<string> { "Road Access", "Clear Title", "Near Market" },
                            Images = new List<string>(),
                            IsApproved = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            IsVerified = true,
                            LegalStatus = "Clear – EC, Patta, Chitta available",
                            MarketingPlan = 0,
                            NearbyLandmarks = new List<string> { "Nagercoil Railway Station (2 km)", "NH 44 (200 m)" },
                            PinCode = "629001",
                            PricePerCent = 150000m,
                            PropertyType = "OpenLand",
                            RoadAccess = true,
                            State = "Tamil Nadu",
                            Status = "ForSale",
                            Title = "15 Cents Prime Land Near Highway – Nagercoil",
                            TotalPrice = 2250000m,
                            UpdatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Town Center",
                            ApprovalStatus = "Approved",
                            AreaInCents = 10m,
                            Bathrooms = 2,
                            Bedrooms = 3,
                            City = "Marthandam",
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ready-to-occupy land with a well-built 3BHK house. All amenities available.",
                            District = "Kanyakumari",
                            Features = new List<string> { "Road Access", "Electricity", "Water Source" },
                            Images = new List<string>(),
                            IsApproved = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            IsVerified = true,
                            MarketingPlan = 0,
                            NearbyLandmarks = new List<string> { "Marthandam Bus Stand (500 m)" },
                            PinCode = "629165",
                            PricePerCent = 450000m,
                            PropertyType = "LandWithBuilding",
                            RoadAccess = true,
                            State = "Tamil Nadu",
                            Status = "ForSale",
                            Title = "10 Cents Land with 3BHK House – Marthandam",
                            TotalPrice = 4500000m,
                            UpdatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pechipparai Road",
                            ApprovalStatus = "Approved",
                            AreaInCents = 50m,
                            City = "Thuckalay",
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fertile agricultural land with natural water source. Ideal for farming.",
                            District = "Kanyakumari",
                            Features = new List<string> { "Water Source", "Fertile Soil" },
                            Images = new List<string>(),
                            IsApproved = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            IsVerified = true,
                            MarketingPlan = 0,
                            NearbyLandmarks = new List<string>(),
                            PinCode = "629175",
                            PricePerCent = 70000m,
                            PropertyType = "Agricultural",
                            RoadAccess = false,
                            State = "Tamil Nadu",
                            Status = "ForSale",
                            Title = "50 Cents Agricultural Land – Thuckalay",
                            TotalPrice = 3500000m,
                            UpdatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RealEstateApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RealEstateApi.Models.SavedProperty", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("SavedProperties");
                });

            modelBuilder.Entity("RealEstateApi.Models.SmsTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableVars")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SmsTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableVars = "name,phone,propertyId,propertyTitle,propertyContext",
                            Body = "Hi {name}, thank you for reaching Jose For Land{propertyContext}. Our team will call you back within 2-5 hours. For urgent help, dial +91 99944 88490.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sent to the public visitor right after they submit an inquiry. Includes the property title when the inquiry was attached to a listing.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "inquiry.confirmation",
                            Label = "Inquiry — visitor confirmation",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AvailableVars = "name,phone,propertyContext",
                            Body = "📩 New inquiry from {name} ({phone}){propertyContext}. Check the admin panel.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifies the admin team whenever a new inquiry comes in.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "inquiry.adminNotification",
                            Label = "Inquiry — admin alert",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AvailableVars = "name,phone",
                            Body = "📨 New inquiry assigned to you: {name} ({phone}). Open the admin panel to review.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifies an employee that an inquiry has been assigned to them.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "inquiry.assignment",
                            Label = "Inquiry — assigned to employee",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AvailableVars = "id,name,actor,prevStatus,newStatus,noteSuffix",
                            Body = "🔔 Inquiry #{id} ({name}) updated by {actor}: {prevStatus} → {newStatus}{noteSuffix}",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifies admins when an employee updates an inquiry status.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "inquiry.statusUpdate",
                            Label = "Inquiry — status changed",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AvailableVars = "name,title",
                            Body = "Hi {name}, thank you for submitting '{title}' on Jose For Land. Our team will review it within 24 hours and get back to you.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sent to a seller after they submit a property for review.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "property.submittedConfirmation",
                            Label = "Property — submitter confirmation",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AvailableVars = "title,priceLakhs,area,name,phone",
                            Body = "🏡 New property pending: '{title}' (₹{priceLakhs}L / {area} cents) from {name} ({phone})",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifies admins of a new property submission awaiting approval.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "property.adminPending",
                            Label = "Property — admin pending alert",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AvailableVars = "name,title",
                            Body = "🎉 Hi {name}, your property '{title}' is now LIVE on Jose For Land! Buyers can now view it. Visit joseforland.com to see it online.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sent to the seller when their property is approved by an admin.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "property.approved",
                            Label = "Property — approved (LIVE)",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AvailableVars = "name,title,reasonSuffix",
                            Body = "Hi {name}, your submission '{title}' could not be approved.{reasonSuffix} Call +91 99944 88490 for help.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sent to the seller if their property is rejected by an admin.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "property.rejected",
                            Label = "Property — rejected",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AvailableVars = "name,phone,propertyId,type",
                            Body = "📄 DOCUMENT REQUEST from {name} ({phone}) for property #{propertyId}. They want to view EC/Patta/Chitta etc. Call them within 2-5 hrs with copies.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifies admins when a buyer requests verified documents for a property.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "inquiry.documentRequest",
                            Label = "Inquiry — document request alert",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AvailableVars = "name,otp,minutes",
                            Body = "Hi {name}, your Jose For Land password reset code is {otp}. Valid for {minutes} minutes. Do not share this code with anyone.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6-digit OTP sent when a user starts the forgot-password flow.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "password.reset.otp",
                            Label = "Password reset — OTP",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AvailableVars = "assigneeFirstName,title,city,submitter,submitterPhone,propertyId",
                            Body = "🏷 Hi {assigneeFirstName}, you've been assigned property #{propertyId} '{title}' in {city} to verify. Seller: {submitter} ({submitterPhone}). Please schedule a site visit.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sent to an Employee/Agent when an admin assigns them a property to verify.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "property.assignedForVerification",
                            Label = "Property — verification assignment",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AvailableVars = "actor,title,propertyId,notes",
                            Body = "✅ {actor} submitted verification for property #{propertyId} '{title}'. Notes: {notes}. Review at /admin/pending/{propertyId}.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notifies admins after the assigned verifier submits their site-visit findings.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "property.verificationSubmitted",
                            Label = "Property — verification submitted",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            AvailableVars = "name,phone,propertyId,propertyTitle,propertyContext",
                            Body = "Hi {name}, your request for documents{propertyContext} has been received. Our team will share EC / Patta / Chitta copies within 2-5 hours. Urgent? Call +91 99944 88490.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sent to the visitor right after they click 'Request to view documents' on a property — calls out that it's a document request and which property it's for.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "inquiry.documentRequestConfirmation",
                            Label = "Inquiry — document request visitor confirmation",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RealEstateApi.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyDetail")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "1:24",
                            Excerpt = "They visited the site with us, explained every document, and stayed honest throughout. Bought my first land through Jose For Land — no regrets.",
                            IsDeleted = false,
                            IsPublished = true,
                            Location = "Nagercoil",
                            Name = "Rajan Kumar",
                            Order = 1,
                            PropertyDetail = "15 cents · Open Land",
                            Rating = 5,
                            Thumbnail = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&q=80&auto=format&fit=crop",
                            UpdatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            VideoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "0:58",
                            Excerpt = "The free doorstep consultation is real — they came to our village, walked the plot with us, and answered every question. Genuine team.",
                            IsDeleted = false,
                            IsPublished = true,
                            Location = "Marthandam",
                            Name = "Priya Selvam",
                            Order = 2,
                            PropertyDetail = "10 cents · Residential Plot",
                            Rating = 5,
                            Thumbnail = "https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=900&q=80&auto=format&fit=crop",
                            UpdatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            VideoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "1:42",
                            Excerpt = "Compared with three other agents — Jose For Land had the cleanest documentation and the most transparent pricing. Highly recommend.",
                            IsDeleted = false,
                            IsPublished = true,
                            Location = "Colachel",
                            Name = "Xavier Joseph",
                            Order = 3,
                            PropertyDetail = "50 cents · Agricultural",
                            Rating = 5,
                            Thumbnail = "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=900&q=80&auto=format&fit=crop",
                            UpdatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            VideoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
                        });
                });

            modelBuilder.Entity("RealEstateApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetOtpHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@joseforland.com",
                            FirstName = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Jose",
                            PasswordHash = "$2a$11$Opgu4SLvHpcA7PeiVkCQnOWlc1Qxa.bWb3SRcqiS4XEZTcNVF/vRC",
                            Phone = "+919994488490",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RealEstateApi.Models.Inquiry", b =>
                {
                    b.HasOne("RealEstateApi.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealEstateApi.Models.Property", "Property")
                        .WithMany("Inquiries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealEstateApi.Models.User", "User")
                        .WithMany("Inquiries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateApi.Models.Property", b =>
                {
                    b.HasOne("RealEstateApi.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealEstateApi.Models.User", "AssignedToVerifyUser")
                        .WithMany()
                        .HasForeignKey("AssignedToVerifyUserId");

                    b.HasOne("RealEstateApi.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("AssignedToVerifyUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("RealEstateApi.Models.RefreshToken", b =>
                {
                    b.HasOne("RealEstateApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateApi.Models.SavedProperty", b =>
                {
                    b.HasOne("RealEstateApi.Models.Property", "Property")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateApi.Models.User", "User")
                        .WithMany("SavedProperties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateApi.Models.Property", b =>
                {
                    b.Navigation("Inquiries");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("RealEstateApi.Models.User", b =>
                {
                    b.Navigation("Inquiries");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SavedProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
